server {
    listen 80;
    server_name wiki.au-team.irpo;

    location / {
        proxy_pass http://172.16.1.2;
    }
}

server {
    listen 80;
    server_name moodle.au-team.irpo;

    location / {
        proxy_pass http://172.16.2.2;
    }
}